-- QSYS2 catalog extracted from pub400.com
CREATE TABLE "AJ_DMART_INFO" (
    "DATA_MART_LIBRARY" TEXT,
    "DATA_MART_TABLE" TEXT,
    "JOURNAL_ENTRY_TYPE" TEXT,
    "DATA_MART_FILTER" TEXT,
    "AUDIT_JOURNAL_STARTING_TIMESTAMP" TEXT,
    "AUDIT_JOURNAL_ENDING_TIMESTAMP" TEXT,
    "BUILD_START" TEXT,
    "BUILD_END" TEXT,
    "BUILD_JOB" TEXT,
    "FAILURE_DETAIL" TEXT
);
CREATE TABLE "DBMON_QUERIES" (
    "QUERYID" TEXT,
    "QUERYREFID" TEXT,
    "QUERYEXTRAPREDICATE" TEXT,
    "QUERYTEXT" TEXT,
    "QUERYSTATEMENT" TEXT
);
CREATE TABLE "OBJECT_TYPES" (
    "OBJECT_TYPE" TEXT
);
CREATE TABLE "QDBOPPCAJ" (
    "JOB_NAME" TEXT,
    "JOB_USER" TEXT,
    "JOB_NUMBER" TEXT
);
CREATE TABLE "QDBOPPCGEN" (
    "HEADING" TEXT,
    "VALUE" TEXT,
    "VALUE_UNITS" TEXT,
    "ENTRY_NUMBER" INTEGER,
    "ENTRY_TYPE" TEXT,
    "GRAPHABLE" TEXT,
    "MINVALUE" TEXT,
    "MAXVALUE" TEXT,
    "DFTVALUE" TEXT,
    "CHANGE_WARNING" TEXT,
    "ENTRY_TIMESTAMP" TEXT,
    "ORDINAL_POSITION" INTEGER
);
CREATE TABLE "QDBOPPCHL" (
    "LAST_TIME_RUN" TEXT,
    "MOST_EXPENSIVE_TIME" NUMERIC,
    "TOTAL_PROCESSING_TIME" NUMERIC,
    "TOTAL_TIMES_RUN" NUMERIC,
    "AVG_PROCESSING_TIME" NUMERIC,
    "SQL_STATEMENT" TEXT,
    "USER_NAME" TEXT,
    "JOB_NAME" TEXT,
    "JOB_USER" TEXT,
    "JOB_NUMBER" TEXT,
    "ADJ_AVG_PROCESSING_TIME" NUMERIC,
    "AVG_RESULT_SET_ROWS" NUMERIC,
    "AVG_TEMP_STORAGE_USED" NUMERIC,
    "PLAN_SCORE" NUMERIC,
    "PLAN_ID" NUMERIC,
    "CACHED_RESULTS_USED" NUMERIC,
    "OPTIMIZATION_TIME" NUMERIC,
    "SYSTEM_NAME" TEXT,
    "RDB_NAME" TEXT,
    "QROHASH" TEXT,
    "QQJFLD" BLOB
);
CREATE TABLE "QDBOPPCJOB" (
    "JOB_NAME" TEXT,
    "JOB_USER" TEXT,
    "JOB_NUMBER" TEXT,
    "FIRST_USED" TEXT,
    "LAST_USED" TEXT
);
CREATE TABLE "QDBOPPCLL" (
    "TIME_OF_RUN" TEXT,
    "PROCESSING_TIME" NUMERIC,
    "USER_NAME" TEXT,
    "JOB_NAME" TEXT,
    "JOB_USER" TEXT,
    "JOB_NUMBER" TEXT,
    "CPU_TIME" NUMERIC,
    "SYNC_DB_READS" NUMERIC,
    "SYNC_NONDB_READS" NUMERIC,
    "ASYNC_DB_READS" NUMERIC,
    "ASYNC_NONDB_READS" NUMERIC,
    "PAGE_FAULTS" NUMERIC,
    "CACHED_RESULT_USED" TEXT,
    "HOST_VARIABLES" TEXT,
    "QQJFLD" BLOB
);
CREATE TABLE "QDBOPPCUSR" (
    "USER_NAME" TEXT,
    "LAST_TIME_RUN" TEXT
);
CREATE TABLE "QSQAJMRI" (
    "MSG_KEY" TEXT,
    "MSG_TEXT" TEXT
);
CREATE TABLE "QSQDB2MMRI" (
    "MSG_KEY" TEXT,
    "MSG_TEXT" TEXT
);
CREATE TABLE "QSQHACTIV" (
    "TIMESTAMP" TEXT,
    "ACTIVITY" TEXT,
    "CURRENT_VALUE" NUMERIC,
    "OBJECT_SCHEMA" TEXT,
    "OBJECT_NAME" TEXT,
    "OBJECT_TYPE" TEXT,
    "SYSTEM_OBJECT_SCHEMA" TEXT,
    "SYSTEM_OBJECT_NAME" TEXT,
    "ACTIVITY_ID" INTEGER,
    "PARTITION_NAME" TEXT,
    "SCHEMA" TEXT,
    "OBJECT" TEXT,
    "REFRESH" INTEGER
);
CREATE TABLE "QSQHENVLIM" (
    "TIMESTAMP" TEXT,
    "LIMIT" TEXT,
    "HIGHWATER_MARK_VALUE" INTEGER,
    "PERCENT" NUMERIC,
    "JOB_NAME" TEXT,
    "CURRENT_USER" TEXT,
    "JOB_TYPE" TEXT,
    "MAXIMUM_VALUE" INTEGER,
    "JOB_STATUS" TEXT,
    "CLIENT_WRKSTNNAME" TEXT,
    "CLIENT_APPLNAME" TEXT,
    "CLIENT_ACCTNG" TEXT,
    "CLIENT_PROGRAMID" TEXT,
    "CLIENT_USERID" TEXT,
    "WHEN_LIMITS_ESTABLISHED" TEXT,
    "INTERFACE_NAME" TEXT,
    "INTERFACE_TYPE" TEXT,
    "INTERFACE_LEVEL" TEXT,
    "LIMIT_ID" INTEGER
);
CREATE TABLE "QSQHLIMITS" (
    "TIMESTAMP" TEXT,
    "LIMIT" TEXT,
    "CURRENT_VALUE" NUMERIC,
    "PERCENT" NUMERIC,
    "OBJECT_SCHEMA" TEXT,
    "OBJECT_NAME" TEXT,
    "OBJECT_TYPE" TEXT,
    "SYSTEM_OBJECT_SCHEMA" TEXT,
    "SYSTEM_OBJECT_NAME" TEXT,
    "MAXIMUM_VALUE" NUMERIC,
    "LIMIT_ID" INTEGER,
    "PARTITION_NAME" TEXT,
    "SCHEMA" TEXT,
    "OBJECT" TEXT,
    "REFRESH" INTEGER
);
CREATE TABLE "QSQHOVER" (
    "TIMESTAMP" TEXT,
    "SCHEMAS" INTEGER,
    "GRP01" TEXT,
    "TABLES" INTEGER,
    "PARTITIONED_TABLES" INTEGER,
    "DISTRIBUTED_TABLES" INTEGER,
    "MATERIALIZED_QUERY_TABLES" INTEGER,
    "PHYSICAL_FILES" INTEGER,
    "SOURCE_FILES" INTEGER,
    "GRP02" TEXT,
    "VIEWS" INTEGER,
    "LOGICAL_FILES" INTEGER,
    "GRP03" TEXT,
    "BINARY_RADIX_INDEXES" INTEGER,
    "EVI_INDEXES" INTEGER,
    "GRP04" TEXT,
    "PRIMARY_KEY_CONSTRAINTS" INTEGER,
    "UNIQUE_CONSTRAINTS" INTEGER,
    "CHECK_CONSTRAINTS" INTEGER,
    "REFERENTIAL_CONSTRAINTS" INTEGER,
    "GRP05" TEXT,
    "EXTERNAL_TRIGGERS" INTEGER,
    "SQL_TRIGGERS" INTEGER,
    "INSTEAD_OF_TRIGGERS" INTEGER,
    "GRP06" TEXT,
    "ALIASES" INTEGER,
    "DDM_FILES" INTEGER,
    "GRP07" TEXT,
    "EXTERNAL_PROCEDURES" INTEGER,
    "SQL_PROCEDURES" INTEGER,
    "GRP08" TEXT,
    "EXTERNAL_SCALAR_FUNCTIONS" INTEGER,
    "EXTERNAL_TABLE_FUNCTIONS" INTEGER,
    "SOURCE_SCALAR_FUNCTIONS" INTEGER,
    "SOURCE_AGGREGATE_FUNCTIONS" INTEGER,
    "SQL_SCALAR_FUNCTIONS" INTEGER,
    "SQL_TABLE_FUNCTIONS" INTEGER,
    "GRP09" TEXT,
    "SEQUENCES" INTEGER,
    "SQL_PACKAGES" INTEGER,
    "USER_DEFINED_DISTINCT_TYPES" INTEGER,
    "JOURNALS" INTEGER,
    "JOURNAL_RECEIVERS" INTEGER,
    "SCHEMA" TEXT
);
CREATE TABLE "QSQPDCMP" (
    "SQL_STATEMENT" TEXT,
    "TOTAL_RUNTIME" NUMERIC,
    "TOTAL_RUNTIME_2" NUMERIC,
    "MAXIMUM_RUNTIME" NUMERIC,
    "MAXIMUM_RUNTIME_2" NUMERIC,
    "AVERAGE_RUNTIME" NUMERIC,
    "AVERAGE_RUNTIME_2" NUMERIC,
    "MINIMUM_RUNTIME" NUMERIC,
    "MINIMUM_RUNTIME_2" NUMERIC,
    "MAXIMUM_OPEN_TIME" NUMERIC,
    "MAXIMUM_OPEN_TIME_2" NUMERIC,
    "MAXIMUM_FETCH_TIME" NUMERIC,
    "MAXIMUM_FETCH_TIME_2" NUMERIC,
    "MAXIMUM_CLOSE_TIME" NUMERIC,
    "MAXIMUM_CLOSE_TIME_2" NUMERIC,
    "STATEMENT_USAGE_COUNT" INTEGER,
    "STATEMENT_USAGE_COUNT_2" INTEGER,
    "FULL_OPENS" INTEGER,
    "FULL_OPENS_2" INTEGER,
    "PSEUDO_OPENS" INTEGER,
    "PSEUDO_OPENS_2" INTEGER,
    "UNIQUE_ACCESS_PLANS" INTEGER,
    "UNIQUE_ACCESS_PLANS_2" INTEGER,
    "AVERAGE_TABLE_SCANS" NUMERIC,
    "AVERAGE_TABLE_SCANS_2" NUMERIC,
    "AVERAGE_INDEXES_USED" NUMERIC,
    "AVERAGE_INDEXES_USED_2" NUMERIC,
    "FULL_INDEXES_CREATED" INTEGER,
    "FULL_INDEXES_CREATED_2" INTEGER,
    "SPARSE_INDEXES_CREATED" INTEGER,
    "SPARSE_INDEXES_CREATED_2" INTEGER,
    "INDEX_FROM_INDEX_CREATED" INTEGER,
    "INDEX_FROM_INDEX_CREATED_2" INTEGER,
    "AVERAGE_INDEX_CREATE_ADVISED" NUMERIC,
    "AVERAGE_INDEX_CREATE_ADVISED_2" NUMERIC,
    "AVERAGE_TEMPORARY_TABLES" NUMERIC,
    "AVERAGE_TEMPORARY_TABLES_2" NUMERIC,
    "AVERAGE_SORTS" NUMERIC,
    "AVERAGE_SORTS_2" NUMERIC,
    "AVERAGE_BITMAP_CREATES" NUMERIC,
    "AVERAGE_BITMAP_CREATES_2" NUMERIC,
    "AVERAGE_MQTS_USED" NUMERIC,
    "AVERAGE_MQTS_USED_2" NUMERIC,
    "MAXIMUM_TABLE_ROWS" NUMERIC,
    "MAXIMUM_TABLE_ROWS_2" NUMERIC,
    "MAXIMUM_ESTIMATED_ROWS" NUMERIC,
    "MAXIMUM_ESTIMATED_ROWS_2" NUMERIC,
    "MAXIMUM_ROWS_RETURNED" NUMERIC,
    "MAXIMUM_ROWS_RETURNED_2" NUMERIC,
    "AVERAGE_TABLE_ROWS" NUMERIC,
    "AVERAGE_TABLE_ROWS_2" NUMERIC,
    "AVERAGE_ESTIMATED_ROWS" NUMERIC,
    "AVERAGE_ESTIMATED_ROWS_2" NUMERIC,
    "AVERAGE_ROWS_RETURNED" NUMERIC,
    "AVERAGE_ROWS_RETURNED_2" NUMERIC,
    "OPTIMIZER_INFORMATION" TEXT,
    "OPTIMIZER_INFORMATION_2" TEXT,
    "AVERAGE_GOVERNOR_TIMEOUTS" NUMERIC,
    "AVERAGE_GOVERNOR_TIMEOUTS_2" NUMERIC,
    "QQJFLD" TEXT,
    "QQJFLD2" TEXT,
    "QQUDEF" TEXT,
    "QQUDEF_2" TEXT,
    "PLAN_SIGNATURE" TEXT,
    "PLAN_SIGNATURE_2" TEXT
);
CREATE TABLE "QSQPDMRI" (
    "MRI_NAME" TEXT,
    "MRI_TEXT" TEXT
);
CREATE TABLE "QSQPLSTEX" (
    "START_TIME" TEXT,
    "MOST_EXPENSIVE_TIME" NUMERIC,
    "TOTAL_PROCESSING_TIME" NUMERIC,
    "TOTAL_TIMES_RUN" NUMERIC,
    "AVERAGE_PROCESSING_TIME" NUMERIC,
    "SQL_STATEMENT" TEXT,
    "USER_NAME" TEXT,
    "JOB_NAME" TEXT,
    "JOB_USER" TEXT,
    "JOB_NUMBER" TEXT,
    "OPTIMIZATION_TIME" NUMERIC,
    "ADJ_AVG_PROCESSING_TIME" NUMERIC,
    "ADVISED_INDEXES" NUMERIC,
    "ADVISED_STATISTICS" NUMERIC,
    "TEMPORARY_STORAGE" NUMERIC,
    "AVERAGE_RESULT_SET_ROWS" NUMERIC,
    "AVG_ROWS_RETURNED_TO_DB" NUMERIC,
    "AVG_ROW_RETRIEVAL_CPU_TIME" NUMERIC,
    "AVG_ROW_RETRIEVAL_CLOCK_TIME" NUMERIC,
    "AVG_SYNCHRONOUS_DB_READS" NUMERIC,
    "AVG_SYNCHRONOUS_DB_WRITES" NUMERIC,
    "AVG_ASYNCHRONOUS_DB_READS" NUMERIC,
    "AVG_ASYNCHRONOUS_DB_WRITES" NUMERIC,
    "AVG_PAGE_FAULTS" NUMERIC,
    "AVG_CALLS_TO_RETRIEVE_ROWS" NUMERIC,
    "SYSTEM_NAME" TEXT,
    "RDB_NAME" TEXT,
    "QQUDEF" TEXT,
    "QRO_HASH" TEXT,
    "QVRCNT" NUMERIC,
    "QQUCNT" NUMERIC,
    "QQJFLD" TEXT
);
CREATE TABLE "QSQPTABL" (
    "INTEGER_COLUMN" INTEGER
);
CREATE TABLE "SERVICES_INFO" (
    "SERVICE_CATEGORY" TEXT,
    "SERVICE_SCHEMA_NAME" TEXT,
    "SERVICE_NAME" TEXT,
    "SQL_OBJECT_TYPE" TEXT,
    "OBJECT_TYPE" TEXT,
    "SYSTEM_OBJECT_NAME" TEXT,
    "LATEST_DB2_GROUP_LEVEL" INTEGER,
    "INITIAL_DB2_GROUP_LEVEL" INTEGER,
    "EARLIEST_POSSIBLE_RELEASE" TEXT,
    "EXAMPLE" TEXT
);
CREATE TABLE "SQL_ERRORT" (
    "LOGGED_SQLCODE" INTEGER,
    "LOGGED_SQLSTATE" TEXT,
    "NUMBER_OCCURRENCES" INTEGER,
    "STATEMENT_TEXT" TEXT,
    "STATEMENT_OPERATION" TEXT,
    "REASON_CODE" INTEGER,
    "PROGRAM_LIBRARY" TEXT,
    "PROGRAM_NAME" TEXT,
    "PROGRAM_TYPE" TEXT,
    "MODULE_NAME" TEXT,
    "LOGGED_TIME" TEXT,
    "JOB_NAME" TEXT,
    "THREAD_ID" INTEGER,
    "ADOPTED_USER_NAME" TEXT,
    "USER_NAME" TEXT,
    "SYSTEM_USER_NAME" TEXT,
    "CLIENT_ACCTNG" TEXT,
    "CLIENT_APPLNAME" TEXT,
    "CLIENT_PROGRAMID" TEXT,
    "CLIENT_USERID" TEXT,
    "CLIENT_WRKSTNNAME" TEXT,
    "RDB_NAME" TEXT,
    "INITIAL_LOGGED_TIME" TEXT,
    "INITIAL_JOB_NAME" TEXT,
    "INITIAL_THREAD_ID" INTEGER,
    "INITIAL_ADOPTED_USER_NAME" TEXT,
    "INITIAL_STACK" TEXT,
    "MESSAGE_TOKENS" TEXT,
    "SQLDA" TEXT,
    "HOST_VARIABLES" TEXT
);
CREATE TABLE "SQL_FEATURES" (
    "FEATURE_ID" TEXT,
    "FEATURE_NAME" TEXT,
    "SUB_FEATURE_ID" TEXT,
    "SUB_FEATURE_NAME" TEXT,
    "IS_SUPPORTED" TEXT,
    "IS_VERIFIED_BY" TEXT,
    "COMMENTS" TEXT
);
CREATE TABLE "SQL_LANGUAGES" (
    "SQL_LANGUAGE_SOURCE" TEXT,
    "SQL_LANGUAGE_YEAR" TEXT,
    "SQL_LANGUAGE_CONFORMANCE" TEXT,
    "SQL_LANGUAGE_INTEGRITY" TEXT,
    "SQL_LANGUAGE_IMPLEMENTATION" TEXT,
    "SQL_LANGUAGE_BINDING_STYLE" TEXT,
    "SQL_LANGUAGE_PROGRAMMING_LANG" TEXT
);
CREATE TABLE "SQL_SIZING" (
    "SIZING_ID" INTEGER,
    "SIZING_NAME" TEXT,
    "SUPPORTED_VALUE" NUMERIC,
    "COMMENTS" TEXT
);
CREATE TABLE "SQLSTATE_INFO" (
    "SQLSTATE_VALUE" TEXT,
    "SQLCODE_VALUE" INTEGER,
    "SQLSTATE_DETAIL" TEXT
);
CREATE TABLE "SYSCHARSETS" (
    "CHARACTER_SET_SCHEMA" TEXT,
    "CHARACTER_SET_NAME" TEXT,
    "DEFAULT_COLLATE_SCHEMA" TEXT,
    "DEFAULT_COLLATE_NAME" TEXT
);
CREATE TABLE "SYSIXADV" (
    "TABLE_SCHEMA" TEXT,
    "PARTITION_NAME" TEXT,
    "KEY_COLUMNS_ADVISED" TEXT,
    "LEADING_COLUMN_KEYS" TEXT,
    "INDEX_TYPE" TEXT,
    "LAST_ADVISED" TEXT,
    "TIMES_ADVISED" INTEGER,
    "ESTIMATED_CREATION_TIME" INTEGER,
    "REASON_ADVISED" TEXT,
    "LOGICAL_PAGE_SIZE" INTEGER,
    "MOST_EXPENSIVE_QUERY" INTEGER,
    "AVERAGE_QUERY_ESTIMATE" INTEGER,
    "TABLE_SIZE" INTEGER,
    "NLSS_TABLE_SCHEMA" TEXT,
    "MTI_USED" INTEGER,
    "MTI_CREATED" INTEGER,
    "LAST_MTI_USED" TEXT,
    "AVERAGE_QUERY_ESTIMATE_MICRO" INTEGER,
    "EVI_DISTINCT_VALUES" INTEGER,
    "INCLUDE_COLUMNS" TEXT,
    "FIRST_ADVISED" TEXT,
    "SYSTEM_TABLE_SCHEMA" TEXT,
    "MTI_USED_FOR_STATS" INTEGER,
    "LAST_MTI_USED_FOR_STATS" TEXT,
    "DEPENDENT_ADVICE_COUNT" INTEGER
);
CREATE TABLE "SYSJARCONTENTS" (
    "JARSCHEMA" TEXT,
    "JAR_ID" TEXT,
    "CLASS" TEXT,
    "CLASS_SOURCE" TEXT,
    "IASP_NUMBER" INTEGER
);
CREATE TABLE "SYSJAROBJECTS" (
    "JARSCHEMA" TEXT,
    "JAR_ID" TEXT,
    "DEFINER" TEXT,
    "JAR_DATA" BLOB,
    "IASP_NUMBER" INTEGER,
    "JAR_CREATED" TEXT,
    "LAST_ALTERED" TEXT,
    "DEBUG_MODE" TEXT,
    "DEBUG_DATA" TEXT
);
CREATE TABLE "SYSLIMTBL" (
    "LAST_CHANGE_TIMESTAMP" TEXT,
    "LIMIT_CATEGORY" INTEGER,
    "LIMIT_TYPE" INTEGER,
    "LIMIT_ID" INTEGER,
    "JOB_NAME" TEXT,
    "USER_NAME" TEXT,
    "CURRENT_VALUE" INTEGER,
    "SYSTEM_SCHEMA_NAME" TEXT,
    "SYSTEM_OBJECT_NAME" TEXT,
    "SYSTEM_TABLE_MEMBER" TEXT,
    "OBJECT_TYPE" TEXT,
    "ASP_NUMBER" INTEGER,
    "IFS_PATH_NAME" TEXT
);
CREATE TABLE "SYSPARMS" (
    "SPECIFIC_SCHEMA" TEXT,
    "SPECIFIC_NAME" TEXT,
    "ORDINAL_POSITION" INTEGER,
    "PARAMETER_MODE" TEXT,
    "PARAMETER_NAME" TEXT,
    "DATA_TYPE" TEXT,
    "NUMERIC_SCALE" INTEGER,
    "NUMERIC_PRECISION" INTEGER,
    "CCSID" INTEGER,
    "CHARACTER_MAXIMUM_LENGTH" INTEGER,
    "CHARACTER_OCTET_LENGTH" INTEGER,
    "NUMERIC_PRECISION_RADIX" INTEGER,
    "DATETIME_PRECISION" INTEGER,
    "IS_NULLABLE" TEXT,
    "LONG_COMMENT" TEXT,
    "ROW_TYPE" TEXT,
    "DATA_TYPE_SCHEMA" TEXT,
    "DATA_TYPE_NAME" TEXT,
    "AS_LOCATOR" TEXT,
    "IASP_NUMBER" INTEGER,
    "NORMALIZE_DATA" TEXT,
    "DEFAULT" TEXT
);
CREATE TABLE "SYSROUTDEP" (
    "SPECIFIC_SCHEMA" TEXT,
    "SPECIFIC_NAME" TEXT,
    "OBJECT_CATALOG" TEXT,
    "OBJECT_SCHEMA" TEXT,
    "OBJECT_NAME" TEXT,
    "OBJECT_TYPE" TEXT,
    "PARM_SIGNATURE" BLOB,
    "IASP_NUMBER" INTEGER,
    "NUMBER_OF_PARMS" INTEGER
);
CREATE TABLE "SYSROUTINES" (
    "SPECIFIC_SCHEMA" TEXT,
    "SPECIFIC_NAME" TEXT,
    "ROUTINE_SCHEMA" TEXT,
    "ROUTINE_NAME" TEXT,
    "ROUTINE_TYPE" TEXT,
    "ROUTINE_CREATED" TEXT,
    "ROUTINE_DEFINER" TEXT,
    "ROUTINE_BODY" TEXT,
    "EXTERNAL_NAME" TEXT,
    "EXTERNAL_LANGUAGE" TEXT,
    "PARAMETER_STYLE" TEXT,
    "IS_DETERMINISTIC" TEXT,
    "SQL_DATA_ACCESS" TEXT,
    "SQL_PATH" TEXT,
    "PARM_SIGNATURE" TEXT,
    "NUMBER_OF_RESULTS" INTEGER,
    "MAX_DYNAMIC_RESULT_SETS" INTEGER,
    "IN_PARMS" INTEGER,
    "OUT_PARMS" INTEGER,
    "INOUT_PARMS" INTEGER,
    "PARSE_TREE" TEXT,
    "PARM_ARRAY" BLOB,
    "LONG_COMMENT" TEXT,
    "ROUTINE_DEFINITION" TEXT,
    "FUNCTION_ORIGIN" TEXT,
    "FUNCTION_TYPE" TEXT,
    "EXTERNAL_ACTION" TEXT,
    "IS_NULL_CALL" TEXT,
    "SCRATCH_PAD" INTEGER,
    "FINAL_CALL" TEXT,
    "PARALLELIZABLE" TEXT,
    "DBINFO" TEXT,
    "SOURCE_SPECIFIC_SCHEMA" TEXT,
    "SOURCE_SPECIFIC_NAME" TEXT,
    "IS_USER_DEFINED_CAST" TEXT,
    "CARDINALITY" INTEGER,
    "FENCED" TEXT,
    "COMMIT_ON_RETURN" TEXT,
    "IASP_NUMBER" INTEGER,
    "NEW_SAVEPOINT_LEVEL" TEXT,
    "LAST_ALTERED" TEXT,
    "DEBUG_MODE" TEXT,
    "DEBUG_DATA" TEXT,
    "ROUNDING_MODE" TEXT,
    "ROUTINE_TEXT" TEXT,
    "SECURE" TEXT,
    "ROUTINE_ENVIRONMENT" BLOB,
    "ROUTINE_DEFAULT_QDT" BLOB,
    "ROUTINE_BIND_OPTION" TEXT,
    "RESTRICT_ON_DROP" TEXT
);
CREATE TABLE "SYSSEQOBJECTS" (
    "SEQUENCE_SCHEMA" TEXT,
    "SEQUENCE_NAME" TEXT,
    "SYSTEM_SEQ_SCHEMA" TEXT,
    "SYSTEM_SEQ_NAME" TEXT,
    "SEQUENCE_DEFINER" TEXT,
    "SEQUENCE_CREATED" TEXT,
    "IASP_NUMBER" INTEGER,
    "SEQUENCE_TEXT" TEXT,
    "LONG_COMMENT" TEXT
);
CREATE TABLE "SYSTEM_OBJECT_TYPES" (
    "OBJECT_TYPE" TEXT,
    "TEXT_DESCRIPTION" TEXT,
    "CATEGORY" TEXT
);
CREATE TABLE "SYSTEXTCOLUMNS" (
    "INDEXID" INTEGER,
    "COLUMNNAME" TEXT,
    "TABLESCHEMA" TEXT,
    "TABLENAME" TEXT,
    "LANGUAGE" TEXT,
    "FUNCTIONSCHEMA" TEXT,
    "FUNCTIONNAME" TEXT,
    "CCSID" INTEGER,
    "FORMAT" TEXT,
    "KEYCOLUMNCOUNT" INTEGER,
    "KEYCOLUMNNAMES" TEXT
);
CREATE TABLE "SYSTEXTCONFIGURATION" (
    "INDEXID" INTEGER,
    "PARAMETER" TEXT,
    "VALUE" TEXT
);
CREATE TABLE "SYSTEXTDEFAULTS" (
    "NAME" TEXT,
    "VALUE" TEXT,
    "TYPE" INTEGER
);
CREATE TABLE "SYSTEXTINDEXES" (
    "INDEXID" INTEGER,
    "INDEXSCHEMA" TEXT,
    "INDEXNAME" TEXT,
    "TABLESCHEMA" TEXT,
    "TABLENAME" TEXT,
    "TABLEIASP" INTEGER,
    "COLLECTIONNAME" TEXT,
    "SERVERID" INTEGER,
    "TAKEOVERSERVERID" INTEGER,
    "TAKEOVERSERVERPULSE" TEXT,
    "SEARCHARGS" BLOB,
    "ALIASSCHEMA" TEXT,
    "ALIASNAME" TEXT,
    "STAGINGTABLENAME" TEXT,
    "EVENTTABLENAME" TEXT,
    "OFINDEXTABLENAME" TEXT,
    "UPDATEMINIMUM" INTEGER,
    "UPDATEFREQUENCY" TEXT,
    "UPDATEMODE" INTEGER,
    "REORGANIZATIONMODE" INTEGER,
    "CREATETIME" TEXT,
    "LASTUPDATETIME" TEXT,
    "LASTUPDATESTATUS" TEXT,
    "SCHEDULERTASKID" INTEGER,
    "EXPRESSIONLISTS" TEXT,
    "EXPRESSIONNUMBERS" BLOB,
    "USEREXITFUNCTION" TEXT,
    "REMARKS" TEXT,
    "TABLEMBR" TEXT
);
CREATE TABLE "SYSTEXTSERVERHISTORY" (
    "INDEXID" INTEGER,
    "SERVERID" INTEGER
);
CREATE TABLE "SYSTEXTSERVERS" (
    "SERVERID" INTEGER,
    "SERVERNAME" TEXT,
    "SERVERADRINFO" BLOB,
    "SERVERPORT" INTEGER,
    "SERVERPATH" TEXT,
    "SERVERTYPE" INTEGER,
    "SERVERAUTHTOKEN" TEXT,
    "SERVERMASTERKEY" TEXT,
    "SERVERCLASS" INTEGER,
    "SERVERSTATUS" INTEGER,
    "ALIASNAME" TEXT
);
CREATE TABLE "SYSTXTLBLS" (
    "COLNAME" TEXT,
    "LABEL" TEXT,
    "TEXT" TEXT
);
CREATE TABLE "SYSTYPES" (
    "USER_DEFINED_TYPE_SCHEMA" TEXT,
    "USER_DEFINED_TYPE_NAME" TEXT,
    "USER_DEFINED_TYPE_DEFINER" TEXT,
    "SOURCE_SCHEMA" TEXT,
    "SOURCE_TYPE" TEXT,
    "SYSTEM_TYPE_SCHEMA" TEXT,
    "SYSTEM_TYPE_NAME" TEXT,
    "METATYPE" TEXT,
    "TYPERULES" TEXT,
    "LENGTH" INTEGER,
    "NUMERIC_SCALE" INTEGER,
    "CCSID" INTEGER,
    "STORAGE" INTEGER,
    "NUMERIC_PRECISION" INTEGER,
    "CHARACTER_MAXIMUM_LENGTH" INTEGER,
    "CHARACTER_OCTET_LENGTH" INTEGER,
    "ALLOCATE" INTEGER,
    "NUMERIC_PRECISION_RADIX" INTEGER,
    "DATETIME_PRECISION" INTEGER,
    "CREATE_TIME" TEXT,
    "LONG_COMMENT" TEXT,
    "IASP_NUMBER" INTEGER,
    "LAST_ALTERED" TEXT,
    "NORMALIZE_DATA" TEXT,
    "TYPE_TEXT" TEXT,
    "MAXIMUM_CARDINALITY" INTEGER
);
CREATE TABLE "SYSVARIABLEDEP" (
    "VARIABLE_SCHEMA" TEXT,
    "VARIABLE_NAME" TEXT,
    "OBJECT_SCHEMA" TEXT,
    "OBJECT_NAME" TEXT,
    "OBJECT_TYPE" TEXT,
    "IASP_NUMBER" INTEGER,
    "PARM_SIGNATURE" BLOB
);
CREATE TABLE "SYSVARIABLES" (
    "VARIABLE_SCHEMA" TEXT,
    "VARIABLE_NAME" TEXT,
    "SYSTEM_VAR_SCHEMA" TEXT,
    "SYSTEM_VAR_NAME" TEXT,
    "VARIABLE_OWNER" TEXT,
    "VARIABLE_DEFINER" TEXT,
    "VARIABLE_CREATED" TEXT,
    "SCOPE" TEXT,
    "OWNER_TYPE" TEXT,
    "USER_DEFINED_TYPE_SCHEMA" TEXT,
    "USER_DEFINED_TYPE_NAME" TEXT,
    "DATA_TYPE" TEXT,
    "LENGTH" INTEGER,
    "NUMERIC_SCALE" INTEGER,
    "STORAGE" INTEGER,
    "NUMERIC_PRECISION" INTEGER,
    "CCSID" INTEGER,
    "CHARACTER_MAXIMUM_LENGTH" INTEGER,
    "CHARACTER_OCTET_LENGTH" INTEGER,
    "NUMERIC_PRECISION_RADIX" INTEGER,
    "DATETIME_PRECISION" INTEGER,
    "DEFAULT" TEXT,
    "IASP_NUMBER" INTEGER,
    "VARIABLE_TEXT" TEXT,
    "LONG_COMMENT" TEXT,
    "DEFAULT_SCHEMA" TEXT,
    "SQL_PATH" TEXT,
    "ROUNDING_MODE" TEXT,
    "READONLY" TEXT
);
CREATE TABLE "XSRANNOTATIONINFO" (
    "XSROBJECTID" INTEGER,
    "ANNOTATION_ID" INTEGER,
    "TABLE_SCHEMA" TEXT,
    "ROWSET" TEXT,
    "COLUMN_NAME" TEXT,
    "DATA_TYPE" INTEGER,
    "INSTANCE_TYPE" INTEGER,
    "TRUNCATE" INTEGER,
    "EXPRESSION" TEXT,
    "CONDITION" TEXT,
    "CAST_EXPRESSION" TEXT,
    "IASP_NUMBER" INTEGER,
    "ROWSET_ORDER" INTEGER
);
CREATE TABLE "XSROBJECTCOMPONENTS" (
    "XSRCOMPONENTID" INTEGER,
    "TARGETNAMESPACE" TEXT,
    "SCHEMALOCATION" TEXT,
    "COMPONENT" BLOB,
    "PROPERTIES" BLOB,
    "CREATED" TEXT,
    "STATUS" TEXT,
    "IASP_NUMBER" INTEGER
);
CREATE TABLE "XSROBJECTHIERARCHIES" (
    "XSROBJECTID" INTEGER,
    "XSRCOMPONENTID" INTEGER,
    "HTYPE" TEXT,
    "TARGETNAMESPACE" TEXT,
    "SCHEMALOCATION" TEXT,
    "IASP_NUMBER" INTEGER
);
CREATE TABLE "XSROBJECTS" (
    "XSROBJECTID" INTEGER,
    "XSROBJECTSCHEMA" TEXT,
    "XSROBJECTNAME" TEXT,
    "SYSTEM_XSR_SCHEMA" TEXT,
    "SYSTEM_XSR_NAME" TEXT,
    "TARGETNAMESPACE" TEXT,
    "SCHEMALOCATION" TEXT,
    "XSR_OBJECT_TEXT" TEXT,
    "GRAMMAR" BLOB,
    "PROPERTIES" BLOB,
    "XSR_SCHEMA_DEFINER" TEXT,
    "XSR_SCHEMA_OWNER" TEXT,
    "XSR_SCHEMA_CREATED" TEXT,
    "STATUS" TEXT,
    "DECOMPOSITION" TEXT,
    "VERSION" TEXT,
    "IASP_NUMBER" INTEGER,
    "LONG_COMMENT" TEXT
);
-- VIEW ASP_INFO definition omitted for brevity
-- VIEW ASP_JOB_INFO definition omitted for brevity
-- VIEW ASP_VARY_INFO definition omitted for brevity
-- VIEW AUDIT_JOURNAL_DATA_MART_INFO definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION_DLO definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION_FSOBJ definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION_IFS definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION_LIBRARIES definition omitted for brevity
-- VIEW AUTHORITY_COLLECTION_OBJECT definition omitted for brevity
-- VIEW AUTHORIZATION_LIST_INFO definition omitted for brevity
-- VIEW AUTHORIZATION_LIST_USER_INFO definition omitted for brevity
-- VIEW AUTHORIZATIONS definition omitted for brevity
-- VIEW AUTOSTART_JOB_INFO definition omitted for brevity
-- VIEW BINDING_DIRECTORY_INFO definition omitted for brevity
-- VIEW BOUND_MODULE_INFO definition omitted for brevity
-- VIEW BOUND_SRVPGM_INFO definition omitted for brevity
-- VIEW CATALOG_NAME definition omitted for brevity
-- VIEW CERTIFICATE_USAGE_INFO definition omitted for brevity
-- VIEW CHARACTER_SETS definition omitted for brevity
-- VIEW CHARACTER_SETS_S definition omitted for brevity
-- VIEW CHECK_CONSTRAINTS definition omitted for brevity
-- VIEW COLLECTION_SERVICES_INFO definition omitted for brevity
-- VIEW COLUMN_PRIVILEGES definition omitted for brevity
-- VIEW COLUMNS definition omitted for brevity
-- VIEW COLUMNS_S definition omitted for brevity
-- VIEW COMMAND_INFO definition omitted for brevity
-- VIEW COMMUNICATIONS_ENTRY_INFO definition omitted for brevity
-- VIEW CONDENSEDINDEXADVICE definition omitted for brevity
-- VIEW CONFIRM_RECLONE_SECURITY_OBJECTS definition omitted for brevity
-- VIEW DATA_AREA_INFO definition omitted for brevity
-- VIEW DATA_QUEUE_INFO definition omitted for brevity
-- VIEW DATABASE_MONITOR_INFO definition omitted for brevity
-- VIEW DB_TRANSACTION_INFO definition omitted for brevity
-- VIEW DRDA_AUTHENTICATION_ENTRY_INFO definition omitted for brevity
-- VIEW ELECTRONIC_SERVICE_AGENT_INFO definition omitted for brevity
-- VIEW ENVIRONMENT_VARIABLE_INFO definition omitted for brevity
-- VIEW EXIT_POINT_INFO definition omitted for brevity
-- VIEW EXIT_PROGRAM_INFO definition omitted for brevity
-- VIEW FUNCTION_INFO definition omitted for brevity
-- VIEW FUNCTION_USAGE definition omitted for brevity
-- VIEW GEOGRAPHIC_MIRRORING_INFO definition omitted for brevity
-- VIEW GROUP_PROFILE_ENTRIES definition omitted for brevity
-- VIEW GROUP_PTF_INFO definition omitted for brevity
-- VIEW HARDWARE_RESOURCE_INFO definition omitted for brevity
-- VIEW HTTP_SERVER_INFO definition omitted for brevity
-- VIEW IFS_MIGRATION_LIST definition omitted for brevity
-- VIEW INFORMATION_SCHEMA_CATALOG_NAME definition omitted for brevity
-- VIEW ISCSI_INFO definition omitted for brevity
-- VIEW JOB_DESCRIPTION_INFO definition omitted for brevity